version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: notification_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications_db
    ports:
      - "5432:5432"
    volumes:
      # Persist data in order to not lose it on container restart
      - postgres_data:/var/lib/postgresql/data
      # Mount our init scripts:
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:6
    container_name: notification_redis
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notification_server
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: notification_client
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

volumes:
  postgres_data: